GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSXZhbiIsImlhdCI6MTYxNTcyNzM2NX0.mJ36M47AkDGMBi40-bk_qQ9tQBSEc9vuKJEnbiuYYek

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Ivan"
}

